// This was auto generated by the VersionWriter.cs script in Assets > Editor
namespace JButler
{
public static class GameVersion
{
    public const string iOS_BuildNumber = "0";
    public const string Android_BuildNumber = "2000";
}
}